---


- hosts: ubuntu
  become: yes
  tasks:
  -  name: Install zabbix-agent on Ubuntu
     apt:
       name=zabbix-agent
       state=latest
     notify:
       zabbix-agent systemd
  - name: Configure the zabbix-agent
    replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '{{item.regexp}}'
        replace: '{{item.replace}}'
    with_items:
        - {regexp: "^Server=127.0.0.1$", replace: Server=158.160.23.51}
        - {regexp: "^ServerActive=127.0.0.1$", replace: ServerActive=158.160.23.51}
        - {regexp: "^Hostname=Zabbix server$", replace: Hostname=zabbix_agent}
  handlers:
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started
